### ISSUE TITLE
PR问题

### ISSUE THREAD

**Issue by wssy001** [xingyuv/captcha-plus#4]
你好  
我看到项目目前是支持`SpringBoot 3`，但是没适配`GraalVM`，不知道你能否接受关于`GraalVM`适配的PR？

**Comment by xingyuv** [comment]
可以的，一会我先创建个分支，然后看一下

**Comment by xingyuv** [comment]
做了一个GraalVM分支，可以先pr到这里

**Comment by wssy001** [comment]
@xingyuv   已提交PR  麻烦看一下
