### ISSUE TITLE
2.x 事宜请教

### ISSUE THREAD

**Issue by wssy001** [xingyuv/captcha-plus#6]
最近看到 `spring-boot-starter-captcha-plus 2.x`版本已经将`springboot`升级到`3.x`
有几个问题希望能得到回答

1. `spring-boot-starter-captcha-plus` 后续版本是否会考虑降级为`springboot 2.x`
2. 如果`spring-boot-starter-captcha-plus`会保持`springboot 3.x`，是否考虑将`graalvm`分支中的一些适配代码纳入到主线分支？

**Comment by xingyuv** [comment]
主分支还是springboot 2.X
2.X分支只是把springboot 升级上去了，如果用springboot2 继续用1.X版本就可以了

**Comment by wssy001** [comment]
> 主分支还是springboot 2.X 2.X分支只是把springboot 升级上去了，如果用springboot2 继续用1.X版本就可以了

`graalvm`分支新增的那些代码最低要求就是`JDK 17  SpringBoot 3.x`，且在进行`Native Image`编译时才会运行
是否考虑将graalvm适配的代码引入到2.x版本？之前PR的时候考虑项目主体还是用`springboot 2.x`  所以没提这个建议

**Comment by wssy001** [comment]
@xingyuv

**Comment by xingyuv** [comment]
> @xingyuv

可以的
